// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon.vue')['default']
    MButton: typeof import('./src/components/MButton.vue')['default']
    MControl: typeof import('./src/components/forms/MControl.vue')['default']
    MControlzz: typeof import('./src/components/forms/MControlzz.vue')['default']
    MDataTable: typeof import('./src/components/MDataTable.vue')['default']
    MField: typeof import('./src/components/forms/MField.vue')['default']
    MInput: typeof import('./src/components/forms/MInput.vue')['default']
    MLabel: typeof import('./src/components/MLabel.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Notifications: typeof import('./src/components/Notifications.vue')['default']
    PreLoader: typeof import('./src/components/PreLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
